[scheduler]
time_limit = 300
min_run_hours = 10
max_lines_per_order = 2
planning_start_date = "2026-02-15 00:00:00"
validate = true

[cip]
interval_h = 120
duration_h = 6

[objective]
makespan_weight = 3
changeover_weight = 120
cip_defer_weight = 10
